# Generated by Django 4.1.10 on 2024-12-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_wish_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='picture',
            field=models.ImageField(default='blank_wish.png', upload_to='wish_images'),
        ),
    ]
